services:
  ui:
    container_name: onecrawler-ui-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5173:5173"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
